-- OUTPUT
-- Table PATIENTS created.


-- Table DOCTORS created.


-- Table APPOINTMENTS created.


-- Table TREATMENT_HISTORY created.


-- Table PRESCRIPTIONS created.

CREATE TABLE Patients (
    patient_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(50) NOT NULL,
    last_name   VARCHAR2(50) NOT NULL,
    dob         DATE NOT NULL,
    gender      VARCHAR2(10) CHECK (gender IN ('Male','Female','Other')) NOT NULL,
    phone       VARCHAR2(15),
    email       VARCHAR2(100) UNIQUE,
    address     CLOB
);

CREATE TABLE Doctors (
    doctor_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR2(50) NOT NULL,
    last_name   VARCHAR2(50) NOT NULL,
    specialty   VARCHAR2(100) NOT NULL,
    phone       VARCHAR2(15),
    email       VARCHAR2(100) UNIQUE,
    department  VARCHAR2(50)
);

CREATE TABLE Appointments (
    appointment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id       NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    appointment_date TIMESTAMP NOT NULL,
    status           VARCHAR2(20) DEFAULT 'Scheduled' CHECK (status IN ('Scheduled','Completed','Canceled')),
    FOREIGN KEY (patient_id) REFERENCES Patients(patient_id),
    FOREIGN KEY (doctor_id) REFERENCES Doctors(doctor_id)
);

CREATE TABLE Treatment_History (
    treatment_id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id         NUMBER NOT NULL,
    diagnosis              CLOB NOT NULL,
    treatment_given        CLOB NOT NULL,
    prescribed_medications CLOB,
    follow_up_required     CHAR(1) DEFAULT 'N' CHECK (follow_up_required IN ('Y', 'N')),
    FOREIGN KEY (appointment_id) REFERENCES Appointments(appointment_id)
);

CREATE TABLE Prescriptions (
    prescription_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id     NUMBER NOT NULL,
    medication_name  VARCHAR2(100) NOT NULL,
    dosage           VARCHAR2(50) NOT NULL,
    frequency        VARCHAR2(50) NOT NULL,
    duration         VARCHAR2(50) NOT NULL,
    FOREIGN KEY (treatment_id) REFERENCES Treatment_History(treatment_id)
);
